LibraryApp/Entities/Report.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryApp.Entities
{
    public class Report
    {
        public string AuthorName { get; set; }

        public string Date { get; set; }
        public string ReportText {get; set;} 

    }
}

LibraryApp/Controllers/GuestPageController.cs
using LibraryApp.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryApp.Controllers
{
    public class GuestPageController : Controller
    {
        List<Report> reportsList = new List<Report>();
        // GET: GuestPage
        public ActionResult Index()
        {
            Report report = new Report();

            report.AuthorName = "A. Smith";
            report.Date = DateTime.Now.ToString();
            report.ReportText = "Reporort 1 Some text";

            reportsList.Add(report);
            reportsList.Add(report);
            ViewBag.ReportsList = reportsList;

            return View(reportsList);
        }


        [HttpPost]
        public ActionResult AddReport(string authorName, string reportText, List<Report> form )
        {
            Report report = new Report() { AuthorName = authorName, ReportText = reportText, Date = DateTime.Now.ToString()};
            reportsList = form;
            reportsList.Add(report);

            return View("Index", reportsList);
        }


    }
}

LibraryApp/Controllers/MainPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryApp.Controllers
{
    public class MainPageController : Controller
    {
        // GET: MainPage
        public ActionResult Index()
        {
            return View();
        }
    }
}

LibraryApp/Controllers/QuestionaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryApp.Controllers
{
    public class QuestionaryController : Controller
    {
        // GET: Questionary
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            ViewBag.email = form["UserEmail"] as string;
            ViewBag.name = form["UserName"] as string;
            ViewBag.html = form["HTML"];
            ViewBag.css = form["CSS"];
            ViewBag.js = form["JS"];
            ViewBag.gender = form["Gender"];
            
            return View("QuestionaryResult"); ;
        }
    }
}

LibraryApp/Views/GuestPage/Index.cshtml
@using LibraryApp.Entities;

@model IList<Report>
@{
    ViewBag.Title = "GuestPage";

}

@using (Html.BeginForm("AddReport", "GuestPage", FormMethod.Post))
{

    <p>
        Author name:
        @Html.TextBox("AuthorName", ViewBag.Text as string)
    </p>
    <p>
        Report text:
        @Html.TextBox("ReportText", ViewBag.Text as string)
    </p>

    for (var i = 0; i < Model.Count; i++)
    {
        @Html.HiddenFor(m => Model[i].AuthorName);
        @Html.HiddenFor(m => Model[i].ReportText);
        @Html.HiddenFor(m => Model[i].Date);
    }

    <input type="submit" name="Button" value="Submit" />
}

@foreach (Report report in Model)
{
    <div class="article">
        @report.AuthorName
        <br />@report.Date
        <br />@report.ReportText
    </div>
}

LibraryApp/Views/MainPage/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="article">
    Назва: Керування погодою і кліматом
    <br />
    Дата публікації: 15/01/2020
    <br />
    Текст:
    <br />
    Клімат — це багаторічний режим погоди, який спостерігається вданій місцевості. Практичне уявлення про клімат одержують на основі статистичної обробки метеорологічних спостережень за багаторічний період (декілька десятків років). Клімат визначають не тільки за середніми значеннями метеорологічних показників, а враховують і їхній річний, добовий хід, їхні крайні значення, середні відхилення від середніх величин, повторюваність певних явищ, середні і крайні строки початку явищ та ін.

    До основних метеорологічних показників клімату належать характеристики стану повітря, а також деякі атмосферні процеси, що безпосередньо спостерігаються на метеорологічних станціях: температура повітря, температура ґрунту, атмосферні опади, тиск, вологість, хмарність, тумани, грози, тривалість сонячного сяйва, висота і стан снігового покриву.

    Клімат залежить від географічної широти певної території, відстані від морів та океанів, характеру морських течій, висоти над рівнем океану, особливості рельєфу.

    Наука про клімат називається кліматологією, її завдання — вивчати та описувати клімат земної кулі.

    Погодою називають сукупність атмосферних процесів і метеорологічних величин, які характеризують фізичний стан атмосфери в певний момент або проміжок часу. Закономірні зміни погоди - це режим погоди. Погода характеризується наступними метеорологічними елементами: сонячна радіація, тривалість сонячного сяяння в годинах, температура повітря і поверхні ґрунту, вологість повітря, атмосферний тиск, вітер, хмарність, опади /кількість, кількість днів з опадами, види опадів, час випадання/, сніговий покрив, горизонтальна видимість, наземні опади та інші атмосферні явища /іній, паморозь, ожеледиця, гроза, тумани, полярні сяйва. веселка, кола й вінці навколо Сонця і Місяця.

    Спостереження за елементами погоди проводяться синхронно на метеостанціях всього світу через кожних три години за гринвіцьким часом. Результати спостережень передаються телеграфом, телефоном або за допомогою радіозв'язку в організації Служби погоди для складання синоптичних карт. Служба погоди виникла в зв'язку з потребою в своєчасній інформації населення, адміністративних і господарських установ про стан погоди, її зміни і передбачення умов погоди на майбутній час. Служба погоди складається з сітки синоптичних станцій і центрально-республіканських, обласних, портових та інших бюро погоди.
</div>
<div class="article">
    Назва: Вивчення будови землі
    <br />
    Дата публікації: 20/04/2019
    <br />
    Текст:
    <br />
    Склад і будова глибинних оболонок Землі в останні десятиліття продовжують залишатися однією з найбільш інтригуючих проблем сучасної геології. Адже Земля володіє однією унікальною особливістю – на ній є життя. Тому всебічне вивчення Землі має величезне значення для людства. Знання про неї служать також своєрідною відправною точкою при вивченні інших планет земної групи. Вчені припускають, що Земля складається з трьох основних частин: ядра, мантії і земної кори.
    Ядро – це центральна, серцевинна частина земної кулі. Воно поки що є загадкою для науки. Впевнено можна казати лише про його радіус – близько 3500 км. Учені вважають, що зовнішня частина ядра перебуває в розплавлено-рідкому стані, а внутрішня – в твердому. Припускають також, що ядро складається з речовини, схожої на метали (із заліза з домішками кремнію або із заліза і нікелю, є й інші припущення). Температура в ядрі досягає 5 0000 С.
    Мантія це – внутрішня оболонка, яка вкриває ядро (з грецької “мантія” – “покривало”). Її потужність майже 3 000 км. Мантія – найбільша з внутрішніх оболонок планети (83 % об’єму Землі). Мантію, як і ядро, ніхто ніколи не бачив. Припускають, що, чим ближче до центра Землі, тим тиск у ній більший, а температура вища: від кількох сотень градусів до +2 500 0С. При такій температурі речовина мантії мала б бути розплавленою, але плавленню заважає великий тиск. Тому вважають, що вона тверда, але водночас і розпечена.
</div>

LibraryApp/Views/Questionary/Index.cshtml
@{
    ViewBag.Title = "Questionary";
}

@helper CreateQuestionary()
{
    using (Html.BeginForm("Index", "Questionary", FormMethod.Post))
    {
    <div style="margin:5px">
        @Html.TextBox("UserEmail", null, new { placeholder = "Enter your Email", style = " width:200px" })
        <br />
        @Html.TextBox("UserName", null, new { placeholder = "Enter your Name", style = " width:200px" })
        <br />
        <span>Skills:</span>
        <br />
        <div style="display:grid; grid-template-columns: 50px 50px; margin-left:40px; width: 100px">
            @Html.CheckBox("HTML", false)
            <span>HTML</span>

            @Html.CheckBox("CSS", false)
            <span>CSS</span>

            @Html.CheckBox("JS", false)
            <span>JS</span>
        </div>
        <br />
        <span>Gender:</span>
        <br />
        <ul style="margin-left:25px; width: 100px">
            <li>
                @Html.RadioButton("Gender", "Male", true)
                <span>Male</span>
            </li>
            <li>
                @Html.RadioButton("Gender", "Female")
                <span>Female</span>
            </li>
        </ul>
        <input type="submit" name="Button" value="Submit" />
    </div>
    }
}

@CreateQuestionary()

LibraryApp/Views/Questionary/QuestionaryResult.cshtml
@{
    ViewBag.Title = "QuestionaryResult";
}

    <div style="margin:5px">
        <span>User email: </span>@ViewBag.email
        <br />
        <span>User name: </span>@ViewBag.name
        <br />
        <span>Skills:</span>
        <ul style="margin-left:25px; width: 100px">
            @if (@ViewBag.html != "false") 
            {
                <li><span>HTML</span></li>
            }
            @if (@ViewBag.css != "false")
            {
                <li><span>CSS</span></li>
            }
            @if (@ViewBag.js != "false")
            {
                <li><span>JS</span></li>
            }
        </ul>
        <span>Gender:</span>
        @ViewBag.gender
    </div>

LibraryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LibraryApp/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/Library.css")

</head>
<div class="header">
    <div id="logo"></div>
    <div id="site-name">Site-Name</div>
</div>

<body>
    

    </div>
    <div class="body-container">
        <div class="body-element" id="Main-body">
            @RenderBody()
        </div>
        <div class="body-element" id="Menu">
            @Html.ActionLink("Main", "Index", "MainPage")
            <br />@Html.ActionLink("Guest", "Index", "GuestPage")
            <br />@Html.ActionLink("Questionary", "Index", "Questionary")
        </div>
        <hr />
    </div>
</body>

<div class="footer">
    <p>Taras Trush | tarastaras144@gmail.com</p>
    <a href="#top">Jump to top of page</a>
</div>
</html>